# Docker - compose này được chạy tren EC2
version: '3.8'

services:
  app:
    image: lenguyenthai/extractdatabasebackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:latest
    expose:
      - "6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password_lenguyenthai
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3304:3306"

volumes:
  mysql-data: