version: '3.8'

services:
  app:
    image: lenguyenthai/extractdatabasebackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
    networks:
      - app_network

  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  es_data:
  mysql-data:
