version: '3.8'

services:
  app:
    image: lenguyenthai/extractdatabasebackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:latest
    expose:
      - "6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    expose:
      - "9200"


