version: '3.8'

services:
  app:
    image: lenguyenthai/extractdatabasebackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
    networks:
      - app_network

  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  es_data: